// Generated from Saver-Market-Products-SYP-Template-1(4).xlsx
// Products: 33

const CUSTOM_PRODUCTS_DATA = [
  {
    "sku": "STK001",
    "nameEn": "BANT ABOUHA Arabic Name Necklace",
    "nameAr": "سلسلة باسم بنت ابوها",
    "descEn": "\"BANT ABOUHA\" Arabic Name Necklace\nA beautiful Arabic calligraphy necklace featuring a stylish and colourful design. Elegant, lightweight, and perfect for everyday wear or as a meaningful gift.",
    "descAr": "سلسلة باسم \"بنت ابوها\"\nقطعة مميزة تجمع بين جمال الخط العربي والألوان الهادئة، لتمنحك إطلالة راقية ولمسة شخصية فريدة. تصميم أنيق يناسب جميع الإطلالات ويعد هدية رائعة لعشاق التفاصيل الجميلة.",
    "price": 650,
    "oldPrice": 750,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "Out of Stock",
    "stockQty": 0,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Whight",
      "Gold",
      "Blue"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Elegant Arabic calligraphy- Stylish colourful finish - Lightweight and comfortable - Perfect for daily wear",
    "specialNotesAr": "تصميم عربي أنيق - ألوان جذابة وعصرية - خفيفة ومريحة للارتداء- مناسبة للاستخدام اليومي",
    "imageCount": 4,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK002",
    "nameEn": "Luxury Necklace, Bracelet & Ring Set",
    "nameAr": "طقم عقد وسوار وخاتم و حلق",
    "descEn": "A sophisticated jewellery set featuring a necklace, bracelet, and ring with a modern flowing design and sparkling accents. Perfect for elegant occasions.",
    "descAr": "طقم فاخر بتصميم عصري\nتميزي بإطلالة راقية مع هذا الطقم الفاخر الذي يضم عقدًا وسوارًا وخاتمًا وحلق بتصميم انسيابي مزين بتفاصيل براقة. قطعة مثالية للمناسبات والسهرات.",
    "price": 1600,
    "oldPrice": 1750,
    "category": "Accessories",
    "brand": "Saver Luxe",
    "availability": "Low Stock",
    "stockQty": 2,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Luxury modern design- Sparkling details - Perfect for parties and events - A thoughtful gift idea",
    "specialNotesAr": "تصميم فاخر وأنيق - لمسة عصرية جذابة - مناسب للحفلات والمناسبات - هدية مميزة وأنيقة",
    "imageCount": 4,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK003",
      "STK004",
      "STK006",
      "STK009",
      "STK013",
      "STK015",
      "STK018",
      "STK020",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK003",
    "nameEn": "Tri-Colour Braided Jewellery Set",
    "nameAr": "طقم ثلاثي الألوان (ذهبي – فضي – روز جولد)",
    "descEn": "A stylish necklace and bracelet set featuring an elegant braided design in gold, silver, and rose gold tones. Versatile and perfect for every outfit.",
    "descAr": "طقم ثلاثي الألوان بتصميم مضفر\nتصميم أنيق يجمع بين الذهبي والفضي والروز جولد في قطعة واحدة، ليمنحك حرية تنسيقه مع مختلف الإطلالات. يتكون من عقد وسوار بتصميم عصري وراقي.",
    "price": 1000,
    "oldPrice": 1250,
    "category": "Accessories",
    "brand": "Saver Luxe",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold",
      "Silver & Rose Gold"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Gold, Silver & Rose Gold - Elegant braided style - Easy to match with any look - Suitable for all occasions",
    "specialNotesAr": "ثلاثة ألوان في قطعة واحدة -تصميم مضفر أنيق - سهل التنسيق مع جميع الإكسسوارات - مناسب لكل المناسبات",
    "imageCount": 5,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK004",
      "STK006",
      "STK009",
      "STK013",
      "STK015",
      "STK018",
      "STK020",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK004",
    "nameEn": "Tri-Colour Beaded Necklace & Hoop Earrings Set",
    "nameAr": "طقم قلادة وأقراط بخرز ثلاثي الألوان",
    "descEn": "A beautiful jewellery set featuring a delicate necklace and matching hoop earrings with shimmering tri-colour beads. Elegant, lightweight, and perfect for any occasion.",
    "descAr": "طقم قلادة وأقراط ثلاثي الألوان\nطقم أنيق مزين بخرز لامع بألوان الذهبي والفضي والروز جولد، يمنحك لمسة من الفخامة والبساطة في الوقت نفسه. مناسب للإطلالات اليومية والمناسبات.",
    "price": 800,
    "oldPrice": 1000,
    "category": "Accessories",
    "brand": "Saver Luxe",
    "availability": "In Stock",
    "stockQty": 2,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold",
      "Silver & Rose Gold"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Gold, Silver & Rose Gold beads -Elegant minimalist design- Lightweight and comfortable -Perfect gift choice",
    "specialNotesAr": "ألوان ثلاثية أنيقة - تصميم ناعم وعصري - خفيف ومريح - خيار رائع للهدايا",
    "imageCount": 5,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK006",
      "STK009",
      "STK013",
      "STK015",
      "STK018",
      "STK020",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK005",
    "nameEn": "Elegant Red Rose Jewellery Set",
    "nameAr": "طقم الورود الحمراء (العقد + السوار + الأقراط)",
    "descEn": "Add a touch of romance to your look with this beautiful jewellery set inspired by blooming roses. Featuring a matching necklace, bracelet, and earrings with a luxurious gold-tone finish and vibrant red rose details, it's perfect for parties, special occasions, or as a thoughtful gift.",
    "descAr": "أضيفي لمسة من الرومانسية إلى إطلالتك مع هذا الطقم الراقي المستوحى من جمال الورود. يتكون من عقد، وسوار، وزوج أقراط بتصميم ذهبي مزين بزهور حمراء لامعة، ليمنحك مظهراً أنثوياً مميزاً يناسب المناسبات والسهرات والهدايا.",
    "price": 800,
    "oldPrice": 850,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Red Rose & Gold"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Elegant rose-inspired design-Luxurious gold-tone finish-Lightweight and comfortable-Perfect for gifts and special occasions",
    "specialNotesAr": "تصميم أنيق مستوحى من الورود - لون ذهبي فاخر مع تفاصيل حمراء جذابة خفيف ومريح للاستخدام اليومي -هدية مثالية للمناسبات الخاصة.",
    "imageCount": 4,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK006",
    "nameEn": "Emerald Green Watch & Jewellery Set",
    "nameAr": "طقم الساعة مع الإكسسوارات باللون الأخضر",
    "descEn": "Complete your elegant look with this luxurious matching set featuring a stylish watch, necklace, earrings, and ring decorated with dazzling emerald-green stones. A perfect combination of sophistication and modern fashion.",
    "descAr": "طقم ساعة وإكسسوارات باللون الأخضر الزمردي\nاستمتعي بإطلالة فاخرة مع هذا الطقم العصري الذي يجمع بين ساعة أنيقة وسلسلة وأقراط وخاتم مزين بأحجار خضراء لامعة. تصميم متناسق يمنحك لمسة من الرقي والأناقة في جميع المناسبات.",
    "price": 850,
    "oldPrice": 1000,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Green",
      "Gold"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Elegant green wristwatch - Sparkling emerald-style stones. - Complete matching jewellery set. Ideal for gifts and special occasions.",
    "specialNotesAr": "ساعة أنيقة بحزام أخضر مميز - أحجار خضراء براقة بتصميم فاخر- طقم متكامل لإطلالة متناسقة - مناسب للهدايا والمناسبات.",
    "imageCount": 5,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK009",
      "STK013",
      "STK015",
      "STK018",
      "STK020",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK007",
    "nameEn": "Tree of Life Bracelet Set",
    "nameAr": "أساور شجرة الحياة",
    "descEn": "Enhance your everyday style with this beautiful bracelet set featuring gold, silver, and rose gold finishes. Each bracelet is adorned with a delicate Tree of Life charm symbolizing strength, growth, and new beginnings.",
    "descAr": "مجموعة أساور شجرة الحياة\nتألقي مع هذه المجموعة الجميلة من الأساور المرنة بتدرجات الذهبي والفضي والذهبي الوردي، والمزينة بقلادة على شكل شجرة الحياة التي ترمز للنمو والقوة والأمل.",
    "price": 400,
    "oldPrice": 500,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold",
      "Silver & Rose Gold"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Modern and elegant design - Gold, silver, and rose gold colours-Comfortable stretch fit -Perfect for daily wear or gifting.",
    "specialNotesAr": "تصميم عصري وأنيق- ثلاثة ألوان جذابة - مرنة ومريحة لمعظم المقاسات - مناسبة للاستخدام اليومي والهدايا.",
    "imageCount": 5,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK008",
    "nameEn": "Luxury Black Flower Jewellery Set",
    "nameAr": "طقم الزهرة السوداء",
    "descEn": "Make a bold statement with this stunning jewellery set featuring a black flower design accented with sparkling crystal details and a rose gold-tone finish. A timeless piece perfect for elegant evenings and special events.",
    "descAr": "طقم زهرة سوداء فاخر\nتميزي بإطلالة راقية مع هذا الطقم الأنيق الذي يضم عقداً، وأقراطاً، وخاتماً بتصميم زهرة سوداء مطعمة بتفاصيل لامعة. تصميم فاخر يجمع بين الكلاسيكية والعصرية ليمنحك حضوراً مميزاً.",
    "price": 650,
    "oldPrice": 750,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Black",
      "Gold"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Elegant floral design -Rose gold-tone finish -Sparkling crystal accents -Perfect for formal occasions and gifting.",
    "specialNotesAr": "تصميم زهري فاخر - لون أسود أنيق مع إطار ذهبي وردي - تفاصيل براقة تضيف لمسة فخامة- مثالي للسهرات والمناسبات الخاصة.",
    "imageCount": 5,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK009",
    "nameEn": "Elegant Rose Gold Jewellery Set",
    "nameAr": "طقم عقد وسوار– لون روز جولد",
    "descEn": "Elevate your style with this stunning rose gold jewellery set featuring a graceful leaf-inspired design adorned with sparkling crystals. Perfect for everyday elegance or special occasions.",
    "descAr": "طقم إكسسوارات روز جولد فاخر\nأضيفي لمسة من الرقي إلى إطلالتك مع هذا الطقم الأنيق بتصميم الأوراق المتشابكة المرصعة بالكريستال اللامع. يتميز بلونه الروز جولد الجذاب الذي يناسب جميع المناسبات، من الإطلالات اليومية إلى السهرات الخاصة.",
    "price": 750,
    "oldPrice": 850,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Red Rose"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Colour: Rose Gold - Sparkling crystal accents - Elegant and modern design - A perfect gift for someone special",
    "specialNotesAr": "اللون: روز جولد - مزين بكريستالات لامعة - تصميم أنيق وعصري - هدية مثالية لكل امرأة أنيقة",
    "imageCount": 2,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK006",
      "STK013",
      "STK015",
      "STK018",
      "STK020",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": "2026-07-15"
  },
  {
    "sku": "STK010",
    "nameEn": "Desert Air Cooler with Fan",
    "nameAr": "مكيف صحراوي مع مروحة",
    "descEn": "A portable evaporative air cooler combined with a powerful fan, designed to provide refreshing cool air in dry and hot environments. Uses water evaporation technology to naturally lower the surrounding temperature, making it an energy-efficient alternative to traditional air",
    "descAr": "جهاز تبريد هواء محمول يعمل بتقنية التبريد التبخيري، يجمع بين مروحة قوية ومكيف صحراوي. صمم لتوفير هواء بارد ومنعش في الأجواء الحارة والجافة، ويعتمد على تبخر الماء لخفض درجة الحرارة المحيطة بشكل طبيعي، مما يجعله بديلاً موفراً للطاقة عن المكيفات التقليدية",
    "price": 1500,
    "oldPrice": 1750,
    "category": "Electronics",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Whight",
      "Rose"
    ],
    "materialEn": "Electronics",
    "materialAr": "الكترونيات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Evaporative cooling technology.\n- 3-speed fan settings.\n- Large water tank for extended use.\n- Energy-efficient and eco-friendly.\n- Portable with built-in handle.\n- Quiet operation for peaceful environment.",
    "specialNotesAr": "- تقنية تبريد تبخيري.\n- 3 سرعات للمروحة.\n- خزان ماء كبير لاستخدام طويل.\n- موفر للطاقة وصديق للبيئة.\n- محمول بمقبض مدمج.\n- تشغيل هادئ لبيئة مريحة",
    "imageCount": 4,
    "collection": "Electronics Collection",
    "tags": [
      "Electronics Collection"
    ],
    "relatedSkus": [
      "STK011",
      "STK014",
      "STK016",
      "STK031",
      "STK033"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK011",
    "nameEn": "360° Rotating Ball Head Stand",
    "nameAr": "ستاند سيلفي وكاميرا برأس دوار 360 درجة",
    "descEn": "A versatile stand featuring a 360° rotating ball head, designed for smartphones, cameras, and action cameras. Allows flexible angle adjustments for the perfect shot, whether for vlogging, photography, or video calls.",
    "descAr": "ستاند متعدد الاستخدامات مزود برأس كروي دوار 360 درجة، مصمم للهواتف الذكية والكاميرات وكاميرات الحركة. يسمح بتعديل الزوايا بمرونة للحصول على أفضل لقطة، سواء للفلوغ أو التصوير أو مكالمات الفيديو",
    "price": 700,
    "oldPrice": 750,
    "category": "Electronics",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Black",
      "blue"
    ],
    "materialEn": "Electronics",
    "materialAr": "الكترونيات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- 360° rotation for any angle.\n- Universal compatibility (phones & cameras).\n- Sturdy and stable base.\n- Easy to adjust and lock.\n- Lightweight and portable.",
    "specialNotesAr": "- دوران 360 درجة لأي زاوية.\n- متوافق مع الهواتف والكاميرات.\n- قاعدة ثابتة ومتينة.\n- سهل التعديل والتثبيت.\n- خفيف ومحمول.",
    "imageCount": 2,
    "collection": "Electronics Collection",
    "tags": [
      "Electronics Collection"
    ],
    "relatedSkus": [
      "STK010",
      "STK014",
      "STK016",
      "STK031",
      "STK033"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK012",
    "nameEn": "Medium-Sized Handbag",
    "nameAr": "حقيبة حجم متوسط",
    "descEn": "A stylish medium-sized handbag that combines fashion and functionality. With ample interior space, it comfortably carries daily essentials while maintaining a sleek and elegant appearance. Perfect for work, shopping, or casual outings.",
    "descAr": "حقيبة يد أنيقة متوسطة الحجم تجمع بين الأناقة والوظائف العملية. مع مساحة داخلية كافية، تحمل مستلزماتك اليومية بشكل مريح مع الحفاظ على مظهر أنيق. مثالية للعمل، التسوق، أو الخرجات اليومية.",
    "price": 1250,
    "oldPrice": 1500,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Whight",
      "pink"
    ],
    "materialEn": "",
    "materialAr": "",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Spacious medium size.\n- Durable and high-quality material.\n- Elegant design for any occasion.\n- Secure closure and comfortable handles.\n- Lightweight yet sturdy.",
    "specialNotesAr": "- حجم متوسط واسع.\n- مادة متينة وعالية الجودة.\n- تصميم أنيق يناسب جميع المناسبات.\n- إغلاق آمن ومقابض مريحة.\n- خفيفة ولكنها متينة.",
    "imageCount": 2,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK013",
    "nameEn": "Silver Ring",
    "nameAr": "خاتم فضي",
    "descEn": "An elegant silver-toned ring with a sleek, minimalist design. Crafted from high-quality metal with a polished finish, it adds a touch of sophistication to any look and is suitable for daily wear or special occasions.",
    "descAr": "خاتم أنيق باللون الفضي بتصميم بسيط وأنيق. مصنوع من معدن عالي الجودة مع تشطيب مصقول، يضيف لمسة من الرقي لأي إطلالة ويناسب الاستخدام اليومي والمناسبات الخاصة.",
    "price": 250,
    "oldPrice": 300,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Silver"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Classic silver finish.\n- Polished scratch-resistant surface.\n- Lightweight and comfortable.\n- Hypoallergenic (nickel-free).\n- Adjustable fit.",
    "specialNotesAr": "- تشطيب فضي كلاسيكي.\n- سطح مصقول مقاوم للخدش.\n- خفيف ومريح.\n- مضاد للحساسية (خالي من النيكل).\n- مقاس قابل للتعديل.",
    "imageCount": 3,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK006",
      "STK009",
      "STK015",
      "STK018",
      "STK020",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK014",
    "nameEn": "Waterproof Mat / Cover",
    "nameAr": "كفر / حماية ضد الماء",
    "descEn": "Durable and stylish protective case designed to safeguard your phone from drops, scratches, and everyday wear. Precise cutouts for all ports and buttons ensure full functionality without removing the case.",
    "descAr": "كفر حماية متين وأنيق يحمي هاتفك من الصدمات والخدوش والتآكل اليومي. يتميز بقواطع دقيقة لجميع المنافذ والأزرار، مما يضمن استخداماً كاملاً للهاتف دون الحاجة لنزع الكفر",
    "price": 500,
    "oldPrice": 600,
    "category": "Electronics",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Whight"
    ],
    "materialEn": "Electronics",
    "materialAr": "الكترونيات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "Shock-absorbent material\n- Precise cutouts for ports & buttons\n- Slim & lightweight design\n- Raised edges for screen & camera protection\n- Anti-slip grip\n- Available in multiple colors\n- Easy to install & remove",
    "specialNotesAr": "- مادة ممتصة للصدمات\n- قواطع دقيقة للمنافذ والأزرار\n- تصميم رفيع وخفيف\n- حواف مرتفعة لحماية الشاشة والكاميرا\n- قبضة مانعة للانزلاق\n- متوفر بألوان متعددة\n- سهل التركيب والإزالة",
    "imageCount": 5,
    "collection": "Electronics Collection",
    "tags": [
      "Electronics Collection"
    ],
    "relatedSkus": [
      "STK010",
      "STK011",
      "STK016",
      "STK031",
      "STK033"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK015",
    "nameEn": "Rabbit-Shaped Earrings",
    "nameAr": "حلق على شكل أرنب",
    "descEn": "A cute pair of earrings designed in the shape of a rabbit. The playful and charming design adds a fun and whimsical touch to any outfit, making it a favorite for casual wear and animal lovers.",
    "descAr": "زوج لطيف من الأقراط بتصميم على شكل أرنب. التصميم المرح والساحر يضيف لمسة ممتعة وجذابة لأي إطلالة، مما يجعله المفضل للإطلالات الكاجوال ولعشاق الحيوانات.",
    "price": 225,
    "oldPrice": 250,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Adorable rabbit shape design.\n- Lightweight and comfortable.\n- Cute and playful aesthetic.\n- Perfect for daily wear.\n- Hypoallergenic material.",
    "specialNotesAr": "- تصميم أرنب لطيف.\n- خفيف ومريح.\n- جمالية مرحة وجذابة.\n- مثالي للارتداء اليومي.\n- مادة مضادة للحساسية.",
    "imageCount": 4,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK006",
      "STK009",
      "STK013",
      "STK018",
      "STK020",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK016",
    "nameEn": "Multi-Connector Adapter Set",
    "nameAr": "علبة وصلات متعددة",
    "descEn": "A versatile set of USB adapter cables including USB to iPhone, Type-C to Type-C, Type-C to iPhone, and Type-C to Micro USB. Perfect for charging and data transfer across multiple devices, making it an essential accessory for everyday use.",
    "descAr": "طقم كابلات محولات متعددة يشمل USB إلى آيفون، Type-C إلى Type-C، Type-C إلى آيفون، وType-C إلى مايكرو USB. مثالي للشحن ونقل البيانات عبر أجهزة متعددة، مما يجعله إكسسوارًا أساسيًا للاستخدام اليومي.",
    "price": 550,
    "oldPrice": 600,
    "category": "Electronics",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Whight"
    ],
    "materialEn": "Electronics",
    "materialAr": "الكترونيات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- 4-in-1 cable set.\n- Supports charging and data transfer.\n- Durable tangle-free design.\n- Compatible with most devices.\n- Compact and portable.",
    "specialNotesAr": "- طقم مكون من 4 وصلات.\n- يدعم الشحن ونقل البيانات.\n- تصميم متين ومقاوم للتشابك.\n- متوافق مع معظم الأجهزة.\n- صغير ومحمول.",
    "imageCount": 4,
    "collection": "Electronics Collection",
    "tags": [
      "Electronics Collection"
    ],
    "relatedSkus": [
      "STK010",
      "STK011",
      "STK014",
      "STK031",
      "STK033"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK017",
    "nameEn": "Butterfly-Transform Neck Collar",
    "nameAr": "طوق يصبح على شكل فراشة وقلوب",
    "descEn": "A magical convertible neck collar that transforms into a beautiful butterfly shape when opened. This innovative design creates two distinct looks in one piece, offering versatility and a touch of whimsical elegance.",
    "descAr": "طوق رقبة سحري يتحول إلى شكل فراشة جميل عند فتحه. هذا التصميم المبتكر يخلق شكلين متميزين في قطعة واحدة، مما يوفر تنوعًا ولمسة من الأناقة المرحة.",
    "price": 650,
    "oldPrice": 750,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Transforms into a butterfly shape.\n- Two looks in one piece.\n- Unique and eye-catching design.\n- Lightweight and comfortable.\n- Perfect for special occasions.",
    "specialNotesAr": "- يتحول إلى شكل فراشة.\n- شكلان في قطعة واحدة.\n- تصميم فريد وجذاب.\n- خفيف ومريح.\n- مثالي للمناسبات الخاصة.",
    "imageCount": 5,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK018",
    "nameEn": "Long Dangle Earrings",
    "nameAr": "حلق طويل",
    "descEn": "A pair of elegant long drop earrings that add sophistication and movement to your look. The elongated design creates a graceful silhouette, perfect for formal events, parties, or adding a touch of glamour to everyday style.",
    "descAr": "زوج من الأقراط الطويلة الأنيقة التي تضيف رقيًا وحركة لإطلالتك. التصميم الممتد يخلق شكلًا أنيقًا، مثالي للمناسبات الرسمية، الحفلات، أو إضافة لمسة من الجمال للإطلالة اليومية.",
    "price": 525,
    "oldPrice": 575,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold",
      "Green"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Sleek elongated design.\n- Lightweight for comfortable wear.\n- Adds elegance and movement.\n- Suitable for various occasions.\n- Tarnish-resistant finish.",
    "specialNotesAr": "- تصميم طويل وأنيق.\n- خفيف للارتداء المريح.\n- يضيف أناقة وحركة.\n- يناسب مختلف المناسبات.\n- تشطيب مقاوم للبهتان.",
    "imageCount": 4,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK006",
      "STK009",
      "STK013",
      "STK015",
      "STK020",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK019",
    "nameEn": "Two-Piece Connected Ring Set",
    "nameAr": "خاتم قطعتين موصولين",
    "descEn": "A unique ring set consisting of two interconnected bands that can be worn together or separately. The innovative linked design symbolizes connection and unity, offering versatile styling options.",
    "descAr": "طقم خواتم فريد مكون من قطعتين مترابطتين يمكن ارتداؤهما معاً أو بشكل منفصل. التصميم المبتكر يرمز للتواصل والوحدة، ويوفر خيارات تنسيق متعددة.",
    "price": 300,
    "oldPrice": 350,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Silver"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Two rings connected by a link.\n- Can be worn together or separately.\n- Adjustable fit.\n- Sleek and modern design.\n- Made from durable silver-tone metal.",
    "specialNotesAr": "- خاتمان متصلان بحلقة وصلة.\n- يمكن ارتداؤهما معاً أو منفصلين.\n- مقاس قابل للتعديل.\n- تصميم أنيق وعصري.\n- مصنوع من معدن فضي متين.",
    "imageCount": 3,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK020",
    "nameEn": "Heart-Shaped Jewelry Set",
    "nameAr": "طقم على شكل قلب",
    "descEn": "A romantic set featuring heart-shaped designs on both the necklace and earrings. Expresses love and affection through its charming shape, making it an ideal gift for loved ones or a sweet addition to your daily style.",
    "descAr": "طقم رومانسي بتصميم قلوب على العقد والأقراط. يعبر عن الحب والمشاعر من خلال شكله الساحر، مما يجعله هدية مثالية للأحباء أو إضافة جميلة لإطلالتك اليومية.",
    "price": 400,
    "oldPrice": 500,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Silver"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Romantic heart-shaped design.\n- Complete set (necklace + earrings).\n- Polished smooth finish.\n- Lightweight and comfortable.\n- Perfect for gifting.",
    "specialNotesAr": "- تصميم قلب رومانسي.\n- طقم كامل (عقد + أقراط).\n- تشطيب مصقول وناعم.\n- خفيف ومريح.\n- مثالي كهدية.",
    "imageCount": 5,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK006",
      "STK009",
      "STK013",
      "STK015",
      "STK018",
      "STK024",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK021",
    "nameEn": "Light-Reflecting Transparent Jewelry Set",
    "nameAr": "طقم شفاف ينعكس الضوء ضمنه",
    "descEn": "A stunning set of transparent accessories that catches and reflects light beautifully. The clear, crystal-like design creates a sparkling effect that adds glamour to any look, perfect for parties and weddings.",
    "descAr": "طقم مذهل من الإكسسوارات الشفافة التي تلتقط وتعكس الضوء بشكل جميل. التصميم الشفاف الشبيه بالكريستال يخلق تأثيراً متلألئاً يضيف رونقاً لأي إطلالة، مثالي للحفلات والأعراس.",
    "price": 500,
    "oldPrice": 600,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Crystal-clear"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Transparent crystal-like material.\n- Reflects light for a sparkling effect.\n- Lightweight and comfortable.\n- Versatile for any outfit.\n- Set includes necklace and earrings.",
    "specialNotesAr": "- مادة شفافة شبيهة بالكريستال.\n- تعكس الضوء لتأثير متلألئ.\n- خفيفة ومريحة.\n- تنسجم مع أي إطلالة.\n- طقم يشمل عقداً وأقراطاً.",
    "imageCount": 5,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK022",
    "nameEn": "Orange Stone Earrings & Neck Collar Set",
    "nameAr": "طقم حلق وطوق بلون أورجواني (برتقالي) مع حجر",
    "descEn": "A matching set consisting of a neck collar and earrings featuring beautiful orange gemstone accents. The warm, vibrant color adds a pop of brightness and elegance, suitable for both day and night wear.",
    "descAr": "طقم متناسق يضم طوق رقبة وأقراطاً مزينة بحجر بلون أورجواني (برتقالي) جميل. اللون الدافئ النابض يضيف لمسة من السطوع والأناقة، مناسب للإطلالات النهارية والمسائية.",
    "price": 750,
    "oldPrice": 800,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold",
      "Rose"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Natural-looking Rose stone details.\n- Coordinated collar and earrings.\n- Secure and durable setting.\n- Eye-catching color.\n- Suitable for various occasions.",
    "specialNotesAr": "- تفاصيل حجر بلون اورجوني طبيعي.\n- طوق وأقراط منسجمة.\n- تثبيت آمن ومتين.\n- لون جذاب يلفت الأنظار.\n- يناسب مختلف المناسبات.",
    "imageCount": 2,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK023",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK023",
    "nameEn": "Black Rose Jewelry Set",
    "nameAr": "طقم وردة سوداء",
    "descEn": "An elegant set featuring a necklace and earrings designed with a black rose motif. The dark, romantic aesthetic adds a bold and sophisticated touch to any outfit, perfect for evening events and special occasions.",
    "descAr": "طقم أنيق يضم عقداً وأقراطاً بتصميم وردة سوداء. الجمالية الداكنة والرومانسية تضيف لمسة جريئة ومتطورة على أي إطلالة، مثالية للمناسبات المسائية والخاصة.",
    "price": 750,
    "oldPrice": 800,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold",
      "Black"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Unique black rose design.\n- Lightweight for comfortable wear.\n- Tarnish-resistant finish.\n- Suitable for formal and casual looks.\n- Complete set (necklace + earrings).",
    "specialNotesAr": "- تصميم وردة سوداء فريد.\n- خفيف للارتداء المريح.\n- تشطيب مقاوم للبهتان.\n- يناسب الإطلالات الرسمية والكاجوال.\n- طقم كامل (عقد + أقراط).",
    "imageCount": 4,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK025",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK024",
    "nameEn": "Full Silver Jewelry Set",
    "nameAr": "طقم فضي كامل",
    "descEn": "A complete elegant set comprising a necklace, bracelet, and ring in a sleek silver finish. Crafted from high-quality silver-tone metal, this set adds a touch of sophistication to any outfit.",
    "descAr": "طقم أنيق ومتكامل مكون من عقد، أسورة، وخاتم بتشطيب فضي أنيق. مصنوع من معدن فضي عالي الجودة، يضفي لمسة من الرقي على أي إطلالة.",
    "price": 1000,
    "oldPrice": 1250,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Silver"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Complete 3-piece set (necklace + bracelet + ring).\n- Shiny scratch-resistant silver finish.\n- Hypoallergenic (nickel-free).\n- Suitable for daily wear and special occasions.\n- Comes in a gift-ready box.",
    "specialNotesAr": "- طقم كامل من 3 قطع (عقد + أسورة + خاتم).\n- تشطيب فضي لامع مقاوم للخدش.\n- مضاد للحساسية (خالي من النيكل).\n- يناسب الاستخدام اليومي والمناسبات الخاصة.\n- يأتي في علبة هدايا جاهزة.",
    "imageCount": 5,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK006",
      "STK009",
      "STK013",
      "STK015",
      "STK018",
      "STK020",
      "STK026",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK025",
    "nameEn": "2-in-1 Magic Jewelry (Ring to Bracelet)",
    "nameAr": "أسورة تتحول إلى خاتم والعكس (قطعة سحرية 2 في 1)",
    "descEn": "An innovative convertible piece that transforms from a ring into a bracelet in seconds. Ingenious design allows you to switch between two looks with a simple twist, offering versatility and style.",
    "descAr": "قطعة مجوهرات مبتكرة قابلة للتحويل، تتحول من خاتم إلى أسورة في ثوانٍ. تصميم عبقر يسمح لك بالتبديل بين شكلين بلفة بسيطة، مما يوفر تنوعاً وأناقة.",
    "price": 750,
    "oldPrice": 800,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Silver"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Converts ring ↔ bracelet instantly.\n- Unique patented mechanism.\n- One piece, two different looks.\n- Lightweight and comfortable.\n- Perfect for travel and daily variety.",
    "specialNotesAr": "- تتحول فوراً بين الخاتم والأسورة.\n- آلية حاصلة على براءة اختراع.\n- قطعة واحدة بشكلين مختلفين.\n- خفيفة ومريحة.\n- مثالية للسفر والتنوع اليومي.",
    "imageCount": 4,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK028",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK026",
    "nameEn": "Neck Collar & Earrings Set",
    "nameAr": "طوق وحلق",
    "descEn": "A matching set featuring a stylish neck collar and a pair of elegant earrings. Designed to complement each other, this duo adds a fashionable and coordinated touch to your look.",
    "descAr": "طقم متناسق يضم طوق رقبة أنيق وزوج من الأقراط الأنيقة. صمم ليكمّل كل منهما الآخر، ويضفي لمسة عصرية ومنسجمة على إطلالتك.",
    "price": 1000,
    "oldPrice": 1250,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Silver",
      "pink"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Coordinated design for perfect harmony.\n- Lightweight for comfortable wear.\n- Suitable for various necklines and face shapes.\n- Durable and tarnish-resistant.\n- Ideal for parties, weddings, and daily wear.",
    "specialNotesAr": "- تصميم متناسق للانسجام التام.\n- خفيف للارتداء المريح.\n- يناسب مختلف أشكال الرقبة والوجه.\n- متين ومقاوم للبهتان.\n- مثالي للحفلات، الأعراس، والاستخدام اليومي.",
    "imageCount": 4,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK006",
      "STK009",
      "STK013",
      "STK015",
      "STK018",
      "STK020",
      "STK024",
      "STK027"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK027",
    "nameEn": "Bracelet & Watch Combo",
    "nameAr": "أسورة وساعة",
    "descEn": "A stylish 2-in-1 set combining an elegant bracelet with a classic watch. Offers the functionality of timekeeping alongside the beauty of jewelry, perfect for everyday elegance.",
    "descAr": "طقم أنيق يجمع بين ساعة كلاسيكية وأسورة أنيقة في قطعة واحدة. يجمع بين وظيفة معرفة الوقت وجمال المجوهرات، مثالي للأناقة اليومية.",
    "price": 750,
    "oldPrice": 800,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Whight",
      "Gold"
    ],
    "materialEn": "Stanstail",
    "materialAr": "ستانل ستيل",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Dual function: watch + bracelet.\n- Adjustable strap for perfect fit.\n- Sleek minimalist design.\n- Lightweight for all-day wear.\n- Suitable for both casual and formal occasions.",
    "specialNotesAr": "- وظيفة مزدوجة: ساعة + أسورة.\n- سوار قابل للتعديل لمقاس مثالي.\n- تصميم أنيق وبسيط.\n- خفيف للارتداء طوال اليوم.\n- يناسب المناسبات الكاجوال والرسمية.",
    "imageCount": 4,
    "collection": "Luxury Collection",
    "tags": [
      "bag",
      "leather",
      "luxury"
    ],
    "relatedSkus": [
      "STK002",
      "STK003",
      "STK004",
      "STK006",
      "STK009",
      "STK013",
      "STK015",
      "STK018",
      "STK020",
      "STK024",
      "STK026"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK028",
    "nameEn": "Nail Art Sticker Decals",
    "nameAr": "لزقات تزيين الأظافر",
    "descEn": "A set of decorative adhesive stickers designed for nail art. Easy to apply and remove, allowing you to create stylish and unique nail designs in seconds without visiting a salon.",
    "descAr": "مجموعة من الملصقات الزخرفية اللاصقة المصممة لتزيين الأظافر. سهلة التركيب والإزالة، تمكنك من ابتكار تصاميم أنيقة وفريدة لأظافرك في ثوانٍ دون الحاجة لزيارة الصالون.",
    "price": 450,
    "oldPrice": 500,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Limited",
    "badgeAr": "كمية محدودة",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "colors"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Quick & easy application.\n- Long-lasting adhesion.\n- Variety of patterns and colors.\n- Salon-quality look at home.\n- Removable without damaging nails.",
    "specialNotesAr": "- تطبيق سريع وسهل.\n- التصاق طويل الأمد.\n- تشكيلة متنوعة من النقوش والألوان.\n- مظهر احترافي في المنزل.\n- قابلة للإزالة دون تلف الأظافر.",
    "imageCount": 5,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK029",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK029",
    "nameEn": "Gold & Silver Classic Bracelet Collection",
    "nameAr": "مجموعة أساور كلاسيكية ذهبية وفضية",
    "descEn": "A pair of elegant bracelets in two classic finishes – shiny gold and sleek silver. Minimalist design with a secure lobster-claw clasp, perfect for daily wear, gifting, or stacking.",
    "descAr": "زوج من الأساور الأنيقة بلونين كلاسيكيين – ذهبي لامع وفضي أنيق. تصميم بسيط مع مشبك آمن على شكل مخلب السلطعون، مثالي للارتداء اليومي، الهدايا، أو التنسيق مع مجوهرات أخرى.",
    "price": 600,
    "oldPrice": 650,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Gold",
      "Silver"
    ],
    "materialEn": "Accessories",
    "materialAr": "اكسسورات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Scratch-resistant polished surface.\n- Lightweight & comfortable.\n- Hypoallergenic (nickel-free).\n- Comes in a gift-ready pouch.",
    "specialNotesAr": "- سطح مصقول مقاوم للخدش.\n- خفيفة ومريحة.\n- مضادة للحساسية (خالية من النيكل).\n- تأتي في كيس هدايا جاه",
    "imageCount": 3,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK030"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK030",
    "nameEn": "Bag Holder / Handbag Stand",
    "nameAr": "حاملة حقائب يدوية",
    "descEn": "A sturdy, compact stand to hold handbags, totes, or backpacks upright. Keeps bags in shape, prevents creasing, and ensures easy access at home, office, or retail.",
    "descAr": "حاملة صغيرة ومتينة لحمل حقائب اليد، الشنط الكبيرة، أو حقائب الظهر بشكل عمودي ومنظم. تحافظ على شكل الحقيبة، تمنع التجاعيد، وتسهل الوصول في المنزل، المكتب، أو المحلات.",
    "price": 900,
    "oldPrice": 1000,
    "category": "Accessories",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "Best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Black"
    ],
    "materialEn": "",
    "materialAr": "",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Strong metal frame with non-slip base.\n- Adjustable width for various sizes.\n- Foldable for easy storage.\n- Protects from dirt & floor damage.",
    "specialNotesAr": "- هيكل معدني قوي بقاعدة مانعة للانزلاق.\n- عرض قابل للتعديل.\n- قابل للطي لتوفير المساحة.\n- يحمي من الأوساخ والتلف الأرضي.",
    "imageCount": 2,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [
      "STK001",
      "STK005",
      "STK007",
      "STK008",
      "STK0012",
      "STK0017",
      "STK019",
      "STK021",
      "STK022",
      "STK023",
      "STK025",
      "STK028",
      "STK029"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK031",
    "nameEn": "Smart Bluetooth Earbuds with AI Power Display",
    "nameAr": "سماعات بلوتوث ذكية مع شاشة طاقة بالذكاء الاصطناعي",
    "descEn": "True wireless stereo earbuds with an AI-powered battery monitor showing exact remaining charge for each earbud and case on a digital screen. Crisp audio, deep bass, and passive noise isolation.",
    "descAr": "سماعات لاسلكية حقيقية (TWS) مزودة بنظام ذكي لمراقبة البطارية يعرض الشحن المتبقي لكل سماعة والعلبة على شاشة رقمية. صوت واضح مع عمق وباس وعزل سلبي للضوضاء.",
    "price": 7500,
    "oldPrice": 900,
    "category": "Electronics",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "best Seller",
    "badgeAr": "الأكثر مبيعاً",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Black"
    ],
    "materialEn": "Electronics",
    "materialAr": "الكترونيات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- AI real-time battery indicator.\n- Up to 6 hrs playback per charge.\n- Touch controls for music/calls.\n- Ergonomic fit with multiple ear tips.",
    "specialNotesAr": "- مؤشر بطارية لحظي بالذكاء الاصطناعي.\n- تشغيل حتى 6 ساعات لكل شحنة.\n- تحكم باللمس للموسيقى والمكالمات.\n- تصميم مريح مع عدة أسوار أذن.",
    "imageCount": 5,
    "collection": "Electronics Collection",
    "tags": [
      "Electronics Collection"
    ],
    "relatedSkus": [
      "STK010",
      "STK011",
      "STK014",
      "STK016",
      "STK033"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK032",
    "nameEn": "Manual Wool Knitting Machine",
    "nameAr": "ماكينة حياكة الصوف اليدوية",
    "descEn": "A compact hand-operated knitting machine for making hats, scarves, gloves, and socks in minutes. No electricity needed – ideal for home crafts, gifts, or small production.",
    "descAr": "ماكينة حياكة صغيرة تعمل يدوياً، تصنع قبعات، أوشحة، قفازات، وجوارب صوفية بدقائق. لا تحتاج كهرباء، مناسبة للأعمال المنزلية، الهدايا، أو الإنتاج البسيط.",
    "price": 2250,
    "oldPrice": 2500,
    "category": "Home Products",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Whight",
      "Pink"
    ],
    "materialEn": "",
    "materialAr": "",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- Portable & lightweight.\n- Easy crank mechanism.\n- Includes beginner instructions.\n- Durable plastic & metal build.",
    "specialNotesAr": "- محمولة وخفيفة.\n- آلية تدوير سهلة.\n- تتضمن تعليمات للمبتدئين.\n- هيكل متين من البلاستيك والمعدن.",
    "imageCount": 4,
    "collection": "Accessory Collection",
    "tags": [
      "scarf",
      "silk",
      "accessory"
    ],
    "relatedSkus": [],
    "reviewCount": 0,
    "dateAdded": ""
  },
  {
    "sku": "STK033",
    "nameEn": "R36MAX Open Source Console",
    "nameAr": "جهاز ألعاب R36MAX المحمول",
    "descEn": "Open-source retro gaming console with 18,000+ pre-installed classic games. 4-inch IPS screen, dual joysticks, and long battery life.",
    "descAr": "جهاز ألعاب محمول مفتوح المصدر مع 18,000+ لعبة كلاسيكية مدمجة. شاشة 4 بوصات IPS، عصيّ تحكم مزدوجة، وبطارية تدوم طويلاً.",
    "price": 7000,
    "oldPrice": 7500,
    "category": "Electronics",
    "brand": "Saver Select",
    "availability": "In Stock",
    "stockQty": 1,
    "featured": true,
    "badgeEn": "New",
    "badgeAr": "جديد",
    "sizes": [
      "Standard"
    ],
    "colors": [
      "Whight"
    ],
    "materialEn": "Electronics",
    "materialAr": "الكترونيات",
    "dimensions": "",
    "weight": "",
    "deliveryTime": "Damascus within 24-48 hours",
    "deliveryTimeAr": "دمشق خلال 24-48 ساعة",
    "specialNotesEn": "- 18,000+ games pre-loaded\n- 4\" IPS HD display\n- 4000mAh battery (7 hrs)\n- RK3326 CPU + 1GB RAM\n- HDMI TV output\n- Dual analog joysticks\n- Type-C charging\n- Supports TF card up to 256GB",
    "specialNotesAr": "- 18,000+ لعبة مدمجة\n- شاشة 4 بوصات IPS HD\n- بطارية 4000mAh (7 ساعات)\n- معالج RK3326 + 1GB رام\n- مخرج HDMI للتلفزيون\n- عصيّ تحكم تناظرية مزدوجة\n- شحن Type-C\n- دعم بطاقة TF حتى 256GB",
    "imageCount": 5,
    "collection": "Electronics Collection",
    "tags": [
      "Electronics Collection"
    ],
    "relatedSkus": [
      "STK010",
      "STK011",
      "STK014",
      "STK016",
      "STK031"
    ],
    "reviewCount": 0,
    "dateAdded": ""
  }
];
